# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.13.3
_src_path: https://github.com/hugoh/go-tools.git
cog_omit_types:
- doc
coverage_total: 100
golangci_extra_disable: []
golangci_extra_exclusions:
-   linters:
    - mnd
    path: thresholds.go
golangci_settings: ''
golangci_test_exclude_linters:
- depguard
- goconst
- varnamelen
has_executable: true
has_fuzz: true
has_gen: false
has_goreleaser: false
has_test_int: true
project_name: cellular-signal
test_int_cmd: test ! -d internal || gotestsum -- -race -tags=integration ./internal/...
testcoverage_excludes: []
testcoverage_overrides: []

