version: "2"
linters:
  default: all
  disable:
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - path: signal_test.go
        linters:
          - varnamelen
  settings:
    errcheck:
      check-blank: true
    mnd:
      ignored-files:
        - thresholds.go
formatters:
  enable:
    - gci
    - gofumpt
    - golines
    - goimports
  exclusions:
    generated: lax
