version: "2"
linters:
  default: all
  disable:
    - paralleltest
    - wsl
  exclusions:
    rules:
      - path: signal_test.go
        linters:
          - depguard
          - varnamelen
      - path: thresholds.go
        linters:
          - mnd
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
