version: "3"

vars:
  COVEROUT: cover.out
  FUNCSOUT: funcs-{{.COVEROUT}}
  GOBIN: $(go env GOPATH)/bin
  TEST_COVERAGE: 100

tasks:
  lint:
    summary: Lint code
    sources: &SOURCES
      - "**/*.go"
      - "**/*.md"
      - "**/*.yml"
    cmds:
      - go mod tidy -diff
      - golangci-lint run ./...
      - prettier --check .

  test:
    summary: Run tests
    cmd: go test ./... -race -coverprofile={{.COVEROUT}} -covermode=atomic

  coverfunc:
    summary: Generate test coverage function
    deps: [test]
    cmd: go tool cover -func={{.COVEROUT}} > {{.FUNCSOUT}}
    sources:
      - "{{.COVEROUT}}"
    generates:
      - "{{.FUNCSOUT}}"

  covercheck:
    summary: Check test coverage
    deps: [coverfunc]
    cmds:
      - cat {{.FUNCSOUT}}
      - |
        awk '/total/{gsub(/%/,"",$3); print "Coverage: " $3 "% (Minimum: {{.TEST_COVERAGE}}%)"; if ($3 < {{.TEST_COVERAGE}}) exit 1}' < "{{.FUNCSOUT}}"

  ci:
    summary: Run CI checks (lint, test, coverage)
    deps: [lint, covercheck]

  clean:
    summary: Clean the project
    cmds:
      - go clean
      - rm -f {{.COVEROUT}} {{.FUNCSOUT}}

  fixlint:
    summary: Fix lint issues
    cmd: golangci-lint run --fix ./...

  fmt:
    summary: Format the code
    sources: *SOURCES
    cmds:
      - golangci-lint fmt ./...
      - prettier --write .

  tidy:
    summary: Tidy the module
    cmd: go mod tidy -v
